services:
  obo:
    image: obo-prd-firebase:latest
    pull_policy: never
    environment:
      API_URL: ${API_URL:?Set API_URL}
      CORS_ORIGINS: ${CORS_ORIGINS:?Set CORS_ORIGINS}
      OBO_AUTH_MODE: ${OBO_AUTH_MODE:?Set OBO_AUTH_MODE}
      OBO_ENCRYPTION_KEY: ${OBO_ENCRYPTION_KEY:?Set OBO_ENCRYPTION_KEY}
      OBO_FIREBASE_PROJECT_ID: ${OBO_FIREBASE_PROJECT_ID:?Set OBO_FIREBASE_PROJECT_ID}
      SURREAL_DATABASE: ${SURREAL_DATABASE:?Set SURREAL_DATABASE}
      SURREAL_NAMESPACE: ${SURREAL_NAMESPACE:?Set SURREAL_NAMESPACE}
      SURREAL_PASSWORD: ${SURREAL_PASSWORD:?Set SURREAL_PASSWORD}
      SURREAL_URL: ${SURREAL_URL:?Set SURREAL_URL}
      SURREAL_USER: ${SURREAL_USER:?Set SURREAL_USER}
